### ISSUE TITLE
Incorrect instructions on README

### ISSUE THREAD

**Issue by Jorijn** [muun/recovery#3]
Hi,

I've been trying out the recovery procedure. The README states I should run `go run -mod=vendor` but that results in an `go run: no go files listed` error.

I did manage to test the recovery procedure successfully with `go run .`.

Did I do something wrong? My OS is Mac OS 10.15.3 and am running `go version go1.13.7 darwin/amd64`.

**Comment by champo** [comment]
Hi @Jorijn! The instructions in the README were missing the last dot, nothing is wrong on your end. They should be `go run -mod=vendor .` this is already corrected in `master`.

There's no behaviour difference between the command you ran and doing so with `-mod=vendor`. The mod flag makes go use the dependencies from the vendor folder instead of downloading them. We added this so the repository is fully self contained.

Thanks for letting us know and sorry for the inconvenience!

**Comment by Jorijn** [comment]
Thanks, @champo
